spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
  application:
    name: AGABUS
  thymeleaf:
    cache: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.xml